if(NOT DEFINED SOURCE OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "SOURCE and OUTPUT are required")
endif()

file(STRINGS "${SOURCE}/classification.tsv" rows)
set(classified_cases "")
set(equation_cases 0)
set(compared_cases 0)
set(pending_cases 0)
set(framework_cases 0)
foreach(row IN LISTS rows)
    if(row MATCHES "^#" OR row STREQUAL "")
        continue()
    endif()
    string(REPLACE "\t" ";" fields "${row}")
    list(LENGTH fields field_count)
    if(NOT field_count EQUAL 4)
        message(FATAL_ERROR "invalid PETSc classification row: ${row}")
    endif()
    list(GET fields 0 case_name)
    list(GET fields 1 case_class)
    list(GET fields 2 comparison_status)
    if(case_name IN_LIST classified_cases)
        message(FATAL_ERROR "duplicate PETSc classification: ${case_name}")
    endif()
    list(APPEND classified_cases "${case_name}")
    if(case_class STREQUAL "equation")
        math(EXPR equation_cases "${equation_cases}+1")
        if(comparison_status STREQUAL "compared")
            math(EXPR compared_cases "${compared_cases}+1")
        elseif(comparison_status STREQUAL "pending")
            math(EXPR pending_cases "${pending_cases}+1")
        else()
            message(FATAL_ERROR "invalid equation status for ${case_name}")
        endif()
    elseif(case_class STREQUAL "framework-self-test" AND
           comparison_status STREQUAL "not-applicable")
        math(EXPR framework_cases "${framework_cases}+1")
    else()
        message(FATAL_ERROR "invalid PETSc class/status for ${case_name}")
    endif()
endforeach()

file(GLOB source_files "${SOURCE}/ex*.c")
set(source_cases "")
foreach(source_file IN LISTS source_files)
    get_filename_component(case_name "${source_file}" NAME_WE)
    list(APPEND source_cases "${case_name}")
    if(NOT case_name IN_LIST classified_cases)
        message(FATAL_ERROR "unclassified PETSc source: ${case_name}")
    endif()
endforeach()
foreach(case_name IN LISTS classified_cases)
    if(NOT case_name IN_LIST source_cases)
        message(FATAL_ERROR "classification has no PETSc source: ${case_name}")
    endif()
endforeach()
list(LENGTH classified_cases classified_count)
list(LENGTH source_cases source_count)
if(source_count EQUAL classified_count)
    set(classification_complete 1)
else()
    set(classification_complete 0)
endif()
file(MAKE_DIRECTORY "${OUTPUT}")
file(WRITE "${OUTPUT}/classification.txt"
    "SMAVE_PETSC_TS_CLASSIFICATION 1\n"
    "SOURCE_CASES ${source_count}\n"
    "CLASSIFIED_CASES ${classified_count}\n"
    "EQUATION_CASES ${equation_cases}\n"
    "FRAMEWORK_SELF_TESTS ${framework_cases}\n"
    "EQUATION_COMPARISONS_COMPLETE ${compared_cases}\n"
    "EQUATION_COMPARISONS_PENDING ${pending_cases}\n"
    "COMPLETE ${classification_complete}\n"
    "END\n")
