foreach(required OUTPUT_MODEL TRAINING_DIR SCENARIO_DIR)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "operator replication generator requires ${required}")
    endif()
endforeach()
set(size 144)
file(REMOVE_RECURSE "${TRAINING_DIR}" "${SCENARIO_DIR}")
file(MAKE_DIRECTORY "${TRAINING_DIR}" "${SCENARIO_DIR}")

set(model "model OperatorPeriodicHelmholtz144\n")
foreach(index RANGE 1 ${size})
    string(APPEND model "  parameter Real b${index} = 1.0;\n")
endforeach()
foreach(index RANGE 1 ${size})
    string(APPEND model "  Real x${index}(start = 0.0, nominal = 1.0);\n")
endforeach()
string(APPEND model "equation\n")
foreach(index RANGE 1 ${size})
    math(EXPR previous_one "${index} - 1")
    math(EXPR previous_two "${index} - 2")
    math(EXPR next_one "${index} + 1")
    math(EXPR next_two "${index} + 2")
    if(previous_one LESS 1)
        math(EXPR previous_one "${previous_one} + ${size}")
    endif()
    if(previous_two LESS 1)
        math(EXPR previous_two "${previous_two} + ${size}")
    endif()
    if(next_one GREATER size)
        math(EXPR next_one "${next_one} - ${size}")
    endif()
    if(next_two GREATER size)
        math(EXPR next_two "${next_two} - ${size}")
    endif()
    string(APPEND model
        "  6*x${index} - 1.4*x${previous_one} - 0.6*x${next_one} - 0.35*x${previous_two} - 0.15*x${next_two} = b${index};\n")
endforeach()
string(APPEND model "end OperatorPeriodicHelmholtz144;\n")
file(WRITE "${OUTPUT_MODEL}" "${model}")

function(write_scenario path sample offset)
    set(content "")
    math(EXPR mode "${sample} % 4")
    foreach(index RANGE 1 ${size})
        math(EXPR stripe "${index} % 9")
        math(EXPR parity "${index} % 2")
        math(EXPR cell "(${index} * 7) % 13")
        math(EXPR scaled "100000 + ${offset} + ${sample} * 170 + ${stripe} * (3 + ${mode}) + ${parity} * ${mode} * 11 + ${cell} * 2")
        math(EXPR whole "${scaled} / 100000")
        math(EXPR fraction "${scaled} % 100000")
        string(APPEND content "b${index}=${whole}.")
        string(LENGTH "${fraction}" fraction_length)
        while(fraction_length LESS 5)
            string(APPEND content "0")
            math(EXPR fraction_length "${fraction_length} + 1")
        endwhile()
        string(APPEND content "${fraction}\n")
    endforeach()
    file(WRITE "${path}" "${content}")
endfunction()

foreach(sample RANGE 0 15)
    set(sample_name "${sample}")
    if(sample LESS 10)
        set(sample_name "0${sample}")
    endif()
    write_scenario("${TRAINING_DIR}/train-${sample_name}.conf" ${sample} 0)
endforeach()
foreach(sample RANGE 0 63)
    set(sample_name "${sample}")
    if(sample LESS 10)
        set(sample_name "0${sample}")
    endif()
    math(EXPR lower_sample "${sample} % 15")
    math(EXPR upper_sample "${lower_sample} + 1")
    math(EXPR interpolation_numerator "${sample} / 15 + 1")
    math(EXPR lower_mode "${lower_sample} % 4")
    math(EXPR upper_mode "${upper_sample} % 4")
    set(content "")
    foreach(index RANGE 1 ${size})
        math(EXPR stripe "${index} % 9")
        math(EXPR parity "${index} % 2")
        math(EXPR cell "(${index} * 7) % 13")
        math(EXPR lower_scaled "100000 + ${lower_sample} * 170 + ${stripe} * (3 + ${lower_mode}) + ${parity} * ${lower_mode} * 11 + ${cell} * 2")
        math(EXPR upper_scaled "100000 + ${upper_sample} * 170 + ${stripe} * (3 + ${upper_mode}) + ${parity} * ${upper_mode} * 11 + ${cell} * 2")
        math(EXPR scaled "((6 - ${interpolation_numerator}) * ${lower_scaled} + ${interpolation_numerator} * ${upper_scaled}) / 6")
        math(EXPR whole "${scaled} / 100000")
        math(EXPR fraction "${scaled} % 100000")
        string(APPEND content "b${index}=${whole}.")
        string(LENGTH "${fraction}" fraction_length)
        while(fraction_length LESS 5)
            string(APPEND content "0")
            math(EXPR fraction_length "${fraction_length} + 1")
        endwhile()
        string(APPEND content "${fraction}\n")
    endforeach()
    file(WRITE "${SCENARIO_DIR}/case-${sample_name}.conf" "${content}")
endforeach()
