if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "phase4 scenario generator requires INPUT and OUTPUT")
endif()
file(REMOVE_RECURSE "${OUTPUT}")
file(MAKE_DIRECTORY "${OUTPUT}")
file(GLOB inputs "${INPUT}/*.conf")
list(SORT inputs)
foreach(input IN LISTS inputs)
    get_filename_component(name "${input}" NAME)
    file(STRINGS "${input}" lines)
    set(output_lines "")
    foreach(line IN LISTS lines)
        if(line MATCHES "^b([0-9]+)=(.*)$")
            set(index "${CMAKE_MATCH_1}")
            if(index LESS_EQUAL 36)
                list(APPEND output_lines "q${index}=${CMAKE_MATCH_2}")
            endif()
        endif()
    endforeach()
    list(JOIN output_lines "\n" content)
    file(WRITE "${OUTPUT}/${name}" "${content}\n")
endforeach()
list(LENGTH inputs input_count)
if(NOT input_count EQUAL 64)
    message(FATAL_ERROR "Phase 4 expected 64 source scenarios, got ${input_count}")
endif()
