foreach(required OUTPUT_MODEL TRAINING_DIR SCENARIO_DIR)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "nonlinear Operator generator missing ${required}")
    endif()
endforeach()

file(MAKE_DIRECTORY "${TRAINING_DIR}" "${SCENARIO_DIR}")
set(model "model NonlinearOperatorGrid4\n  parameter Real p = 1.0;\n")
foreach(index RANGE 1 16)
    string(APPEND model "  Real x${index}(start=0, nominal=2);\n")
endforeach()
string(APPEND model "equation\n")
foreach(row RANGE 0 3)
    foreach(column RANGE 0 3)
        math(EXPR index "${row} * 4 + ${column} + 1")
        string(APPEND model "  4*x${index} + 0.02*x${index}^3")
        if(row GREATER 0)
            math(EXPR neighbor "${index} - 4")
            string(APPEND model " - x${neighbor}")
        endif()
        if(row LESS 3)
            math(EXPR neighbor "${index} + 4")
            string(APPEND model " - x${neighbor}")
        endif()
        if(column GREATER 0)
            math(EXPR neighbor "${index} - 1")
            string(APPEND model " - x${neighbor}")
        endif()
        if(column LESS 3)
            math(EXPR neighbor "${index} + 1")
            string(APPEND model " - x${neighbor}")
        endif()
        string(APPEND model " = p + 0.01*${index};\n")
    endforeach()
endforeach()
string(APPEND model "end NonlinearOperatorGrid4;\n")
file(WRITE "${OUTPUT_MODEL}" "${model}")

foreach(index RANGE 0 15)
    math(EXPR scaled "50 + ${index} * 10")
    math(EXPR whole "${scaled} / 100")
    math(EXPR fraction "${scaled} % 100")
    if(fraction LESS 10)
        set(fraction "0${fraction}")
    endif()
    file(WRITE "${TRAINING_DIR}/train-${index}.conf" "p=${whole}.${fraction}\n")
endforeach()

foreach(index RANGE 0 63)
    math(EXPR permuted "(${index} * 29) % 64")
    math(EXPR scaled "52 + ${permuted} * 23 / 10")
    math(EXPR whole "${scaled} / 100")
    math(EXPR fraction "${scaled} % 100")
    if(fraction LESS 10)
        set(fraction "0${fraction}")
    endif()
    if(index LESS 10)
        set(name "case-0${index}.conf")
    else()
        set(name "case-${index}.conf")
    endif()
    file(WRITE "${SCENARIO_DIR}/${name}" "p=${whole}.${fraction}\n")
endforeach()
