if(NOT DEFINED CORE OR NOT DEFINED EX30 OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "CORE, EX30 and OUTPUT are required")
endif()
file(READ "${CORE}" core)
file(READ "${EX30}" ex30)
foreach(required IN ITEMS
    "CASES 16"
    "AGREEMENTS 16"
    "AGREEMENT 1")
    if(NOT core MATCHES "${required}")
        message(FATAL_ERROR "missing ${required} in PETSc core comparison")
    endif()
endforeach()
if(NOT ex30 MATCHES "AGREEMENT 1")
    message(FATAL_ERROR "ex30 comparison did not agree")
endif()
foreach(field IN ITEMS ERROR TOLERANCE PETSC_RESIDUAL_INF SMAVE_RESIDUAL_INF UNKNOWNS SMAVE_ITERATIONS PETSC_SECONDS SMAVE_SECONDS SMAVE_VS_PETSC_SPEEDUP)
    string(REGEX MATCH "${field} ([0-9.eE+-]+)" match "${ex30}")
    if(NOT match)
        message(FATAL_ERROR "missing ${field} in ex30 comparison")
    endif()
    set(ex30_${field} "${CMAKE_MATCH_1}")
endforeach()
set(ex30_case
    "CASE \"ex30\" METHOD \"BEuler-grid-Landau\" AGREEMENT 1 ERROR ${ex30_ERROR} TOLERANCE ${ex30_TOLERANCE} PETSC_RESIDUAL_INF ${ex30_PETSC_RESIDUAL_INF} SMAVE_RESIDUAL_INF ${ex30_SMAVE_RESIDUAL_INF} UNKNOWNS ${ex30_UNKNOWNS} SMAVE_ITERATIONS ${ex30_SMAVE_ITERATIONS} PETSC_SECONDS ${ex30_PETSC_SECONDS} SMAVE_SECONDS ${ex30_SMAVE_SECONDS} SMAVE_VS_PETSC_SPEEDUP ${ex30_SMAVE_VS_PETSC_SPEEDUP}\n")
string(REPLACE "SMAVE_PETSC_TS_COMPARISON 6" "SMAVE_PETSC_TS_COMPARISON 7" core "${core}")
string(REPLACE "CASES 16" "CASES 17" core "${core}")
string(REPLACE "AGREEMENTS 16" "AGREEMENTS 17" core "${core}")
string(REPLACE "METHOD \"BEuler\"\n" "${ex30_case}METHOD \"BEuler\"\n" core "${core}")
file(WRITE "${OUTPUT}" "${core}")
