foreach(required SHADOW_AUDIT CANARY_AUDIT MANIFEST_ONE MANIFEST_TWO STATE STATUS_OUTPUT SOLVE_OUTPUT KEY_PERMISSION_REPORT TAMPER_REJECTION ORIGINAL_STATUS_AFTER_TAMPER DATASET_TAMPER_REJECTION ORIGINAL_STATUS_AFTER_DATASET_TAMPER)
    if(NOT DEFINED ${required} OR NOT EXISTS "${${required}}")
        message(FATAL_ERROR "missing Phase 7 artifact: ${required}")
    endif()
endforeach()
file(READ "${KEY_PERMISSION_REPORT}" key_permissions)
if(UNIX AND NOT key_permissions MATCHES "OWNER_ONLY 1")
    message(FATAL_ERROR "Phase 7 signing key is not owner-only")
endif()
get_filename_component(store_directory "${STATE}" DIRECTORY)
foreach(release phase7-r1 phase7-r2)
    foreach(payload parent.audit model.ir expert.artifact certificate.verify dataset.manifest runtime.bundle release.audit release.manifest)
        if(NOT EXISTS "${store_directory}/releases/${release}/${payload}")
            message(FATAL_ERROR "immutable release lacks payload ${payload}: ${release}")
        endif()
    endforeach()
endforeach()
file(READ "${SHADOW_AUDIT}" shadow)
foreach(pattern
    "STAGE \"shadow\""
    "DATASET_ID \"phase7-validation-scenarios\""
    "DATASET_VERSION \"[0-9a-f]+\""
    "TRAFFIC_FRACTION 0"
    "SAFETY_EVALUATIONS 64"
    "ERRONEOUS_ACCEPT_RATE_UPPER_BOUND 0.0[0-9]+"
    "MAX_ERRONEOUS_ACCEPT_RATE 0.05"
    "PROMOTION_READY 1")
    if(NOT shadow MATCHES "${pattern}")
        message(FATAL_ERROR "shadow gate evidence missing: ${pattern}")
    endif()
endforeach()
get_filename_component(phase7_directory "${SHADOW_AUDIT}" DIRECTORY)
file(READ "${phase7_directory}/operator.expert" operator_artifact)
file(READ "${phase7_directory}/operator.verify" operator_certificate)
foreach(pattern
    "SMAVE_LATENT_OPERATOR 2"
    "TRAINING_DATASET_ID \"phase7-operator-training\""
    "TRAINING_DATASET_VERSION \"[0-9a-f]+\""
    "TRAINING_DATASET_MANIFEST_HASH \"[0-9a-f]+\"")
    if(NOT operator_artifact MATCHES "${pattern}")
        message(FATAL_ERROR "operator training lineage missing: ${pattern}")
    endif()
endforeach()
foreach(pattern
    "SMAVE_VERIFIED_CELLS 2"
    "TRAINING_DATASET_ID \"phase7-operator-training\""
    "TRAINING_DATASET_VERSION \"[0-9a-f]+\""
    "TRAINING_DATASET_MANIFEST_HASH \"[0-9a-f]+\"")
    if(NOT operator_certificate MATCHES "${pattern}")
        message(FATAL_ERROR "operator certificate training lineage missing: ${pattern}")
    endif()
endforeach()
string(REGEX MATCH "TRAINING_DATASET_VERSION \"([0-9a-f]+)\"" _ "${operator_artifact}")
set(artifact_training_version "${CMAKE_MATCH_1}")
string(REGEX MATCH "TRAINING_DATASET_VERSION \"([0-9a-f]+)\"" _ "${operator_certificate}")
set(certificate_training_version "${CMAKE_MATCH_1}")
if(NOT artifact_training_version STREQUAL certificate_training_version)
    message(FATAL_ERROR "operator artifact and certificate training versions differ")
endif()
file(READ "${phase7_directory}/validation.txt" validation)
file(READ "${phase7_directory}/performance.txt" performance)
foreach(report IN ITEMS validation performance)
    foreach(pattern
        "dataset_id=phase7-validation-scenarios"
        "dataset_version=[0-9a-f]+"
        "dataset_manifest_hash=[0-9a-f]+")
        if(NOT "${${report}}" MATCHES "${pattern}")
            message(FATAL_ERROR "${report} dataset lineage missing: ${pattern}")
        endif()
    endforeach()
endforeach()
if(operator_artifact MATCHES "TRAINING_DATASET_ID \"phase7-validation-scenarios\"")
    message(FATAL_ERROR "training and validation datasets must remain distinct")
endif()
file(READ "${SOLVE_OUTPUT}" solve)
foreach(pattern "release: phase7-r1" "signature_verified: 1" "status: success")
    if(NOT solve MATCHES "${pattern}")
        message(FATAL_ERROR "signed production solve evidence missing: ${pattern}")
    endif()
endforeach()
file(READ "${CANARY_AUDIT}" canary)
foreach(pattern "STAGE \"canary\"" "TRAFFIC_FRACTION 0.1" "PARENT_AUDIT_HASH \"[0-9a-f]+\"" "PROMOTION_READY 1")
    if(NOT canary MATCHES "${pattern}")
        message(FATAL_ERROR "canary gate evidence missing: ${pattern}")
    endif()
endforeach()
foreach(manifest_path "${MANIFEST_ONE}" "${MANIFEST_TWO}")
    file(READ "${manifest_path}" manifest)
    foreach(pattern "KEY_ID" "DATASET_MANIFEST_SHA256" "MANIFEST_HASH" "SIGNATURE")
        if(NOT manifest MATCHES "${pattern} \"[0-9a-f]+\"")
            message(FATAL_ERROR "signed manifest evidence missing: ${pattern}")
        endif()
    endforeach()
endforeach()
file(READ "${STATE}" state)
foreach(pattern "GENERATION 3" "CURRENT \"phase7-r1\"" "PREVIOUS \"phase7-r2\"")
    if(NOT state MATCHES "${pattern}")
        message(FATAL_ERROR "rollback state evidence missing: ${pattern}")
    endif()
endforeach()
file(READ "${STATUS_OUTPUT}" status)
foreach(pattern "signature_verified: 1" "current_release: phase7-r1" "dataset_id: phase7-validation-scenarios" "dataset_version: [0-9a-f]+")
    if(NOT status MATCHES "${pattern}")
        message(FATAL_ERROR "active release verification missing: ${pattern}")
    endif()
endforeach()
file(READ "${TAMPER_REJECTION}" tamper_rejection)
foreach(pattern "EXPECTED_FAILURE 1" "release artifact digest binding failed")
    if(NOT tamper_rejection MATCHES "${pattern}")
        message(FATAL_ERROR "copied-store tamper rejection evidence missing: ${pattern}")
    endif()
endforeach()
file(READ "${ORIGINAL_STATUS_AFTER_TAMPER}" original_status)
foreach(pattern "signature_verified: 1" "current_release: phase7-r1")
    if(NOT original_status MATCHES "${pattern}")
        message(FATAL_ERROR "authoritative store failed after copied-store tamper: ${pattern}")
    endif()
endforeach()
file(READ "${DATASET_TAMPER_REJECTION}" dataset_tamper_rejection)
foreach(pattern "EXPECTED_FAILURE 1" "dataset manifest")
    if(NOT dataset_tamper_rejection MATCHES "${pattern}")
        message(FATAL_ERROR "copied-store dataset tamper rejection missing: ${pattern}")
    endif()
endforeach()
file(READ "${ORIGINAL_STATUS_AFTER_DATASET_TAMPER}" original_dataset_status)
foreach(pattern "signature_verified: 1" "current_release: phase7-r1" "dataset_id: phase7-validation-scenarios")
    if(NOT original_dataset_status MATCHES "${pattern}")
        message(FATAL_ERROR "authoritative store failed after dataset tamper: ${pattern}")
    endif()
endforeach()
message(STATUS "Phase 7 signed promotion, rollback, private-key and tamper gates passed")
