foreach(required COUPLED_REPORT CUBIC_REPORT COUPLED_VALIDATION CUBIC_VALIDATION COUPLED_TRACES CUBIC_TRACES)
    if(NOT DEFINED ${required} OR NOT EXISTS "${${required}}")
        message(FATAL_ERROR "missing Phase 1 artifact: ${required}")
    endif()
endforeach()
get_filename_component(phase1_directory "${COUPLED_REPORT}" DIRECTORY)
get_filename_component(phase1_directory "${phase1_directory}" DIRECTORY)
foreach(family IN ITEMS coupled cubic)
    file(READ "${phase1_directory}/${family}/affine.expert" artifact)
    file(READ "${phase1_directory}/${family}/affine.verify" certificate)
    foreach(pattern "SMAVE_AFFINE 2" "TRAINING_DATASET_ID" "TRAINING_DATASET_VERSION" "TRAINING_DATASET_MANIFEST_HASH")
        string(FIND "${artifact}" "${pattern}" found)
        if(found EQUAL -1)
            message(FATAL_ERROR "Phase 1 ${family} artifact training lineage missing ${pattern}")
        endif()
    endforeach()
    foreach(pattern "SMAVE_VERIFIED_CELLS 2" "TRAINING_DATASET_ID" "TRAINING_DATASET_VERSION" "TRAINING_DATASET_MANIFEST_HASH")
        string(FIND "${certificate}" "${pattern}" found)
        if(found EQUAL -1)
            message(FATAL_ERROR "Phase 1 ${family} certificate training lineage missing ${pattern}")
        endif()
    endforeach()
endforeach()
foreach(report_path "${COUPLED_REPORT}" "${CUBIC_REPORT}")
    file(READ "${report_path}" report)
    foreach(required "SMAVE_PERFORMANCE 2" "same_accuracy=1" "baseline_failures=0" "accelerated_failures=0" "gate_mismatches=0")
        string(FIND "${report}" "${required}" found)
        if(found EQUAL -1)
            message(FATAL_ERROR "Phase 1 performance report missing ${required}: ${report_path}")
        endif()
    endforeach()
    foreach(required "repetitions=100" "bootstrap_samples=10000")
        string(FIND "${report}" "${required}" found)
        if(found EQUAL -1)
            message(FATAL_ERROR "Phase 1 statistical protocol missing ${required}: ${report_path}")
        endif()
    endforeach()
    foreach(pattern "dataset_version=[0-9a-f]+" "dataset_manifest_hash=[0-9a-f]+" "report_hash=[0-9a-f]+")
        if(NOT report MATCHES "${pattern}")
            message(FATAL_ERROR "Phase 1 performance lineage missing ${pattern}: ${report_path}")
        endif()
    endforeach()
    string(REGEX MATCH "baseline_mean_iterations=([0-9.eE+-]+)" baseline_match "${report}")
    set(baseline "${CMAKE_MATCH_1}")
    string(REGEX MATCH "accelerated_mean_iterations=([0-9.eE+-]+)" accelerated_match "${report}")
    set(accelerated "${CMAKE_MATCH_1}")
    if(NOT baseline_match OR NOT accelerated_match OR NOT accelerated LESS baseline)
        message(FATAL_ERROR "Phase 1 warm-start did not reduce mean iterations: ${report_path}")
    endif()
endforeach()
file(READ "${COUPLED_REPORT}" coupled_report)
if(NOT coupled_report MATCHES "dataset_id=phase1-coupled-evaluation")
    message(FATAL_ERROR "Phase 1 coupled performance dataset identity missing")
endif()
file(READ "${CUBIC_REPORT}" cubic_report)
if(NOT cubic_report MATCHES "dataset_id=phase1-cubic-evaluation")
    message(FATAL_ERROR "Phase 1 cubic performance dataset identity missing")
endif()
foreach(validation_path "${COUPLED_VALIDATION}" "${CUBIC_VALIDATION}")
    file(READ "${validation_path}" validation)
    foreach(required "SMAVE_VALIDATION 3" "erroneous_accepts=0" "full_fallbacks=0" "original_solver_failures=0" "top_k_target_met=1" "safety_target_met=1")
        string(FIND "${validation}" "${required}" found)
        if(found EQUAL -1)
            message(FATAL_ERROR "Phase 1 validation missing ${required}: ${validation_path}")
        endif()
    endforeach()
endforeach()
foreach(trace_directory "${COUPLED_TRACES}" "${CUBIC_TRACES}")
    file(GLOB_RECURSE traces "${trace_directory}/*.trace")
    if(NOT traces)
        message(FATAL_ERROR "Phase 1 trace directory is empty: ${trace_directory}")
    endif()
    foreach(trace_path IN LISTS traces)
        file(READ "${trace_path}" trace)
        foreach(pattern "BLOCK block-1 WARM_START_ACCEPT" "SUMMARY direct=0" "warm_start=1" "fallback=0")
            string(FIND "${trace}" "${pattern}" found)
            if(found EQUAL -1)
                message(FATAL_ERROR "Phase 1 warm-start permission/path evidence missing ${pattern}: ${trace_path}")
            endif()
        endforeach()
    endforeach()
endforeach()
message(STATUS "Phase 1 two-family warm-start convergence, iteration reduction, and safety gates passed")
