if(NOT EXISTS "${SNAPSHOT}" OR NOT EXISTS "${REPEAT}" OR NOT EXISTS "${VERIFY}")
    message(FATAL_ERROR "data registry evidence output is missing")
endif()
file(READ "${SNAPSHOT}" snapshot)
file(READ "${REPEAT}" repeat)
file(READ "${VERIFY}" verify)
string(REGEX MATCH "version: ([0-9a-f]+)" _ "${snapshot}")
set(version "${CMAKE_MATCH_1}")
string(REGEX MATCH "version: ([0-9a-f]+)" _ "${repeat}")
set(repeat_version "${CMAKE_MATCH_1}")
string(LENGTH "${version}" version_length)
if(NOT version_length EQUAL 64 OR NOT version STREQUAL repeat_version)
    message(FATAL_ERROR "dataset snapshots are not deterministic SHA-256 versions")
endif()
foreach(output IN ITEMS snapshot repeat verify)
    if(NOT "${${output}}" MATCHES "dataset: validation-scenarios" OR
       NOT "${${output}}" MATCHES "files: 2" OR
       NOT "${${output}}" MATCHES "verified: 1")
        message(FATAL_ERROR "${output} lacks verified dataset evidence")
    endif()
endforeach()
if(NOT EXISTS "${STORE}/datasets/validation-scenarios/${version}/dataset.manifest")
    message(FATAL_ERROR "content-addressed dataset manifest is missing")
endif()
